-- CREATING DATABASE
CREATE DATABASE SALES;
USE SALES;

-- CREATING TABLE
CREATE TABLE ORDERS (
Order_Id INT primary key auto_increment, 
Customer_name varchar(50) NOT NULL, 
Product_Category VARCHAR(50), 
Ordered_item VARCHAR(50), 
Contact_No VARCHAR(15) unique
);

-- Add a new column named “order_quantity” to the orders table
ALTER TABLE ORDERS ADD COLUMN ORDER_QUANTITY INT;

-- Rename the orders table to the sales_orders table
RENAME TABLE ORDERS TO SALES_ORDERS;

DESC SALES_ORDERS;

-- Insert 10 rows into the sales_orders table
INSERT INTO SALES_ORDERS
VALUES
(DEFAULT,'MICHEAL TOM','FURNITURE','BOOKCASES','+919876543210',10),
(DEFAULT,'ANGEL MARK','OFFICE SUPPLIES','BINDERS','+917776543270',2),
(DEFAULT,'ALLEN BROWN','TECHNOLOGY','PHONE','+918876543218',5),
(DEFAULT,'TIM GROOK','FURNITURE','CHAIR','+916676548810',7),
(DEFAULT,'MELINDA ROBUST','TECHNOLOGY','TELEVISION','+915576543256',15),
(DEFAULT,'PENINCA MIKE','TECHNOLOGY','SMART WATCH','+914476543219',3),
(DEFAULT,'JAMES SMITH','OFFICE SUPPLIES','PAPER','+913476543217',20),
(DEFAULT,'RAKE NOON','TECHNOLOGY','PHONE','+918976543210',15),
(DEFAULT,'ADAM NIKE','TECHNOLOGY','PHONE','+911076543210',8),
(DEFAULT,'ETHEN SNOWS','OFFICE SUPPLIES','STORAGE','+911176543210',1);

-- Retrieve customer_name and Ordered_Item from the sales_orders table. 
SELECT CUSTOMER_NAME, ORDER_QUANTITY FROM SALES_ORDERS;

SELECT * FROM SALES_ORDERS;

-- Use the update command to change the name of the product for any row
UPDATE SALES_ORDERS SET Product_Category = 'ELECTRONICS' WHERE Order_Id = 5;

-- Delete the sales_orders table from the database
DROP TABLE SALES_ORDERS;

